package com.ruomm.base.common.greendao;

import com.ruomm.base.ioc.annotation.NotProguard;
import com.ruomm.baseconfig.BaseConfig;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
@NotProguard
public class BaseDaoMaster extends AbstractDaoMaster {
	// public static final int SCHEMA_VERSION = 1;

	/** Creates underlying database table using DAOs. */
	public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
		DBEntryValueDao.createTable(db, ifNotExists);
	}

	/** Drops underlying database table using DAOs. */
	public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
		DBEntryValueDao.dropTable(db, ifExists);
	}

	public static abstract class OpenHelper extends SQLiteOpenHelper {

		public OpenHelper(Context context, String name, CursorFactory factory) {
			super(context, name, factory, BaseConfig.Base_DBEntryStore_Version);
		}

		@Override
		public void onCreate(SQLiteDatabase db) {
			Log.i("greenDAO", "Creating tables for schema version " + BaseConfig.Base_DBEntryStore_Version);
			createAllTables(db, false);
		}
	}

	/** WARNING: Drops all table on Upgrade! Use only during development. */
	public static class DevOpenHelper extends OpenHelper {
		public DevOpenHelper(Context context, String name, CursorFactory factory) {
			super(context, name, factory);
		}

		@Override
		public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
			Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion
					+ " by dropping all tables");
			dropAllTables(db, true);
			onCreate(db);
		}
	}

	public BaseDaoMaster(SQLiteDatabase db) {
		super(db, BaseConfig.Base_DBEntryStore_Version);
		registerDaoClass(DBEntryValueDao.class);
	}

	@Override
	public BaseDaoSession newSession() {
		return new BaseDaoSession(db, IdentityScopeType.Session, daoConfigMap);
	}

	@Override
	public BaseDaoSession newSession(IdentityScopeType type) {
		return new BaseDaoSession(db, type, daoConfigMap);
	}

}
