package com.ruomm.base.common.greendao;

import java.util.Map;

import com.ruomm.base.ioc.annotation.NotProguard;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
@NotProguard
public class BaseDaoSession extends AbstractDaoSession {

	private final DaoConfig dBEntryValueDaoConfig;

	private final DBEntryValueDao dBEntryValueDao;

	public BaseDaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		dBEntryValueDaoConfig = daoConfigMap.get(DBEntryValueDao.class).clone();
		dBEntryValueDaoConfig.initIdentityScope(type);

		dBEntryValueDao = new DBEntryValueDao(dBEntryValueDaoConfig, this);

		registerDao(DBEntryValue.class, dBEntryValueDao);
	}

	public void clear() {
		dBEntryValueDaoConfig.getIdentityScope().clear();
	}

	public DBEntryValueDao getDBEntryValueDao() {
		return dBEntryValueDao;
	}

}
