package com.ruomm.base.common.greendao;

import com.ruomm.base.ioc.annotation.NotProguard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBENTRY_VALUE.
 */
@NotProguard
public class DBEntryValue {

	private Long id;
	/** Not-null value. */
	private String key;
	private String tag;
	private String value;
	private String valueTag;
	/** Not-null value. */
	private java.util.Date updateTime;

	public DBEntryValue() {
	}

	public DBEntryValue(Long id) {
		this.id = id;
	}

	public DBEntryValue(Long id, String key, String tag, String value, String valueTag, java.util.Date updateTime) {
		this.id = id;
		this.key = key;
		this.tag = tag;
		this.value = value;
		this.valueTag = valueTag;
		this.updateTime = updateTime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/** Not-null value. */
	public String getKey() {
		return key;
	}

	/** Not-null value; ensure this value is available before it is saved to the database. */
	public void setKey(String key) {
		this.key = key;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getValueTag() {
		return valueTag;
	}

	public void setValueTag(String valueTag) {
		this.valueTag = valueTag;
	}

	/** Not-null value. */
	public java.util.Date getUpdateTime() {
		return updateTime;
	}

	/** Not-null value; ensure this value is available before it is saved to the database. */
	public void setUpdateTime(java.util.Date updateTime) {
		this.updateTime = updateTime;
	}

}
